### Language setup files:
#Tag of language
LANGUAGE=esc

#Vocabulary threshold
LM_VOCAB=2

#Number of induced clusters
LANG_CL=47

# Number of test instances of [LANGUAGE] We need to fix this!!
NTEST=118424

# Add feature for punctuation marks
DIS_FEAT_OPT=

#Experiments
include ../Makefile
