### Language setup files:
#Tag of language
LANGUAGE=enw

#Vocabulary threshold
LM_VOCAB=20
MINI_LM_VOCAB=500

#Number of induced clusters
LANG_CL=45

# Number of test instances of [LANGUAGE] We need to fix this!!
NTEST=1173766

# Add feature for punctuation marks
DIS_FEAT_OPT=

include ../Makefile
