### Language setup files:
#Tag of language
LANGUAGE=enw

#Vocabulary threshold
LM_VOCAB=20

#Number of induced clusters
LANG_CL=45

# Number of test instances of [LANGUAGE] We need to fix this!!
NTEST=1173766

include ../Makefile
