all:
	cd dists; make
	cd fastsubs; make
	cd scode; make
	cd wkmeans; make
	cd wordsub; make

clean:
	cd dists; make clean
	cd fastsubs; make clean
	cd scode; make clean
	cd wkmeans; make clean
	cd wordsub; make clean
