### Language setup files:
#Tag of language
LANGUAGE=bgc

#Vocabulary threshold
LM_VOCAB=2

#Number of induced clusters
LANG_CL=54

# Number of test instances of [LANGUAGE] We need to fix this!!
NTEST=118424

#Experiments
include ../Makefile
